# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c5d8efa9ccd39b4163c8e4ee400f25fe"
name = "BlogGen (dev)"
handle = "blog-gen"
application_url = "https://supplied-cruz-extraction-fabrics.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,write_content"

[auth]
redirect_urls = [
  "https://supplied-cruz-extraction-fabrics.trycloudflare.com/auth/callback",
  "https://supplied-cruz-extraction-fabrics.trycloudflare.com/auth/shopify/callback",
  "https://supplied-cruz-extraction-fabrics.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscription"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/app/compliance"

[pos]
embedded = false

[build]
dev_store_url = "nocturna-digital-testing.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
