# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6bc44285f5684fd901ba3afdbd475adb"
name = "Blog Agent (dev)"
handle = "blog-agent"
application_url = "https://notification-inns-findlaw-with.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files"

[auth]
redirect_urls = [
  "https://notification-inns-findlaw-with.trycloudflare.com/auth/callback",
  "https://notification-inns-findlaw-with.trycloudflare.com/auth/shopify/callback",
  "https://notification-inns-findlaw-with.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscription"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/app/compliance"

[pos]
embedded = false

[build]
dev_store_url = "nocturna-digital-testing.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
